### ISSUE TITLE
loader `.find` doesn't seem to be batching calls

### ISSUE THREAD

**Issue by ericuldall** [feathersjs-ecosystem/dataloader#6]
I have a virtual resolvers like so:
```
listItems: virtual(async (item, context) => {
    return context.params.loader.service('lists').find({
      ...getAuthenticatedParams(context),
      query: { $select: ['name', 'path'], _id: { $in: item.lists } },
    }).then(l => l.data);
  })
```

And when logging my lists service I'm not seeing any batched requests. Am I missing something?

**Comment by ericuldall** [comment]
Also seems like .load doesn't like it when I pass `query: { $select: ['name', 'path'] }`

**Comment by DaddyWarbucks** [comment]
`.find` does not do any "batching". It is really only a cached find. Use the `.load` method for batching.

**Comment by ericuldall** [comment]
Okay good to know. I've been digging in the docs some more and slowly learning all the ways to use load.

**Comment by DaddyWarbucks** [comment]
I've been meaning to update the docs and make them better. I know they aren't great. Sorry.
